# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a50a49c019a09aacd7b90a7bedb1b7075bbdb98a27e540192e0c49431bafabb7c9a92c212dc29fdeb9ac41156df6b16cf66dcd85bbbc5e0630bf42d2c7827d8

test:
  secret_key_base: a436344c3b96ccf58b5148d5dcccb39dffc8f57ae8d3b3d9fb67f66687d7a89ae88fa98a26127e32e0a054bc7f8ae787743259da08209781a13271ee9a405c54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
